Add contribution guidelines
Pradumnasaraf/Twitter_Bot pull request #25
Opened 2023-02-19 12:39 UTC by thevinitgupta

## 🛠️ Fixes Issue

Close #9 

## 👨‍💻 Changes proposed

Add contribution guidelines

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2023-02-19 13:13 UTC, Pradumnasaraf requested changes
Just a blank line need to added

2023-02-19 13:13 UTC, Pradumnasaraf commented on CONTRIBUTING.md
> +> **Pull Requests having no issue associated with them will not be accepted. Firstly get an issue assigned, whether it's already opened or raised by you, and then create a Pull Request.**
```suggestion
> **Pull Requests having no issue associated with them will not be accepted. Firstly get an issue assigned, whether it's already opened or raised by you, and then create a Pull Request.**

```

2023-02-19 13:22 UTC, thevinitgupta commented
I have made the required changes

2023-02-19 13:24 UTC, Pradumnasaraf commented
Hey,  I have requested to add a blank like after line 3. You can check comment here https://github.com/Pradumnasaraf/Botchain/pull/25#discussion_r1111234456

2023-05-03 10:58 UTC, Pradumnasaraf approved these changes
Looks good to merge :tada:.

2023-05-03 10:58 UTC, merged